version: '3.7'

services:

  redis:
    build:
      context: ./docker/redis
    volumes:
      - .:/var/www
    ports:
      - "6379:6379"
    networks:
      - backend

  php:
    build: ./docker/php
    ports:
      - "9001:9001"
    tty: true
    restart: on-failure
    links:
      - redis
    volumes:
      - .:/var/www:cached
      - ./var/log:/var/www/var/log:cached
    extra_hosts:
      - "docker-host.local:127.0.0.1"
    networks:
      - backend

  nginx:
    build: ./docker/nginx
    ports:
      - "8081:80"
    tty: true
    restart: always
    depends_on:
      - php
      - redis
    volumes:
      - ./var/log/nginx:/var/log/nginx:cached
      - .:/var/www:cached
    extra_hosts:
      - "firestorm.local:127.0.0.1"
    networks:
      - backend

networks:
  backend:
    driver: "bridge"