version: '3.7'

services:

  redis:
    container_name: "firestorm_redis"
    build:
      context: ./docker/redis
    volumes:
      - .:/var/www
    ports:
      - "6379:6379"

  firestorm:
    container_name: "firestorm_php"
    build: ./docker/php
    ports:
      - "9000:9001"
    tty: true
    links:
      - redis
    volumes:
      - .:/var/www:cached
      - ./var/log:/var/www/var/log:cached
    extra_hosts:
      - "docker-host.local:127.0.0.1"

  nginx:
    container_name: "firestorm_nginx"
    build: ./docker/nginx
    ports:
      - "8081:80"
    tty: true
    links:
      - firestorm
    volumes:
      - ./var/log/nginx:/var/log/nginx:cached
      - .:/var/www:cached

networks:
  backend:
    driver: "bridge"