rest.calculate_area.post:
  path: /api/v1/missile/calculate-area
  methods: [POST]
  controller: Firestorm\MonCalamari\Ui\Api\Controller\CalculateAreaController

rest.calculate_area.get:
  path: /api/v1/missile/calculate-area/{uuid}
  methods: [GET]
  controller: Firestorm\MonCalamari\Ui\Api\Controller\GetAreaByIdController
